name: ab_assessment
description: "An assessment task for a job"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/screenshots/

  fonts:
    - family: Karla
      fonts:
        - asset: fonts/Karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: fonts/Karla/Karla-Light.ttf
          weight: 300
        - asset: fonts/Karla/Karla-Regular.ttf
          weight: 400
        - asset: fonts/Karla/Karla-Medium.ttf
          weight: 500
        - asset: fonts/Karla/Karla-SemiBold.ttf
          weight: 600
        - asset: fonts/Karla/Karla-Bold.ttf
          weight: 700
        - asset: fonts/Karla/Karla-ExtraBold.ttf
          weight: 800

        - asset: fonts/Karla/Karla-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Karla/Karla-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Karla/Karla-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Karla/Karla-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Karla/Karla-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Karla/Karla-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Karla/Karla-ExtraBoldItalic.ttf
          weight: 800
          style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

